### ISSUE TITLE
Fuel not consuming after artifact upgrade

### ISSUE THREAD

**Issue by BryBTG** [InZidiuZ/LegacyFuel#53] opened 2020-03-28 13:30 UTC
After i upgraded my artifacts to 2270 fuel consumption is not working,.

**Comment by Gbronski** [comment] 2020-03-29 02:54
We've got the same but we haven't update the artifact. Been good for months and bam

**Comment by BryBTG** [comment] 2020-03-29 03:50
@Gbronski have figured out the reason ?

**Comment by camsqu** [comment] 2020-03-29 05:43
I am experiencing the same issue here, also haven't updated the artifact. Based on the FiveM client changelog I'm fairly sure it has to do with this commit https://github.com/citizenfx/fivem/commit/913a10efe1d5f662b09088620f78fd509dc9401c

**Comment by BryBTG** [comment] 2020-03-29 07:01
I see, if you guys have any update, just comment up on this issue. Thank you!

**Comment by camsqu** [comment] 2020-03-29 08:57
FiveM Client just received an update that seemed to fix the issue for me. Looks like someone at FiveM just made a typo or something when working on RPM calculations https://github.com/citizenfx/fivem/commit/0141261b0de2b05e08a5e265e38a7f71c0803de5

**Comment by BryBTG** [comment] 2020-03-29 10:10
So we are just gonna wait for it to be applied right ? @camsqu

**Comment by camsqu** [comment] 2020-03-29 17:10
It should already be fixed when you next launch your FiveM client. For me it was an automatic update late last night. The issue was fixed in client version 2310 if you check the change logs. @BryBTG

**Comment by InZidiuZ** [comment] 2022-01-07 21:55
This was indeed an issue caused by FiveM, so closing.

**Closed by InZidiuZ** 2022-01-07 21:55 UTC
