### ISSUE TITLE
player character bug and cant do anything

### ISSUE THREAD

**Issue by ali-exacute** [InZidiuZ/LegacyFuel#40] opened 2019-07-26 07:20 UTC
so , after refilling car , (jerrycans most of the time) , characters get freeze,cant get inside car , cant access phone , cant do anything at all
but after you drop jerrycan , everything will work fine
tried to remove disablecontrol, nothing good happend

**Comment by InZidiuZ** [comment] 2019-08-18 10:28
Never had this issue, guessing it's another resource causing this, *or* you made some bad changes to the script. Try using it on a server with *only* the base resources and see if it's still an issue.

Closing as I'm unable to reproduce it, though.

**Closed by InZidiuZ** 2019-08-18 10:28 UTC
